[versions]
# Android SDK
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
jvmToolchain = "21"

# Plugins
androidGradlePlugin = "8.13.1"
kotlin = "2.2.21"
kotlinCompose = "2.2.21"
ksp = "2.3.3"
googleServices = "4.4.4"
firebaseCrashlytics = "3.0.6"

# Core libraries
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
tensorflowLite = "2.17.0"
preferenceKtx = "1.2.1"
okhttp = "5.3.2"

# Compose
composeBom = "2025.12.00"
activityCompose = "1.12.1"

# Navigation
navigationCompose = "2.9.6"

# Other libraries
uriKmp = "0.0.21"
playServicesLocation = "21.3.0"
kotlinxCoroutinesPlayServices = "1.10.2"
koin = "4.1.1"
kotlinxSerializationJson = "1.9.0"
retrofitKotlinxSerializationConverter = "1.0.0"
okhttpLoggingInterceptor = "5.3.2"

# Firebase
firebaseBom = "34.6.0"

# Room
room = "2.8.4"

[libraries]
# Core libraries
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
tensorflow-lite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Other libraries
eygraber-uri-kmp = { group = "com.eygraber", name = "uri-kmp", version.ref = "uriKmp" }
google-android-gms-playServicesLocation = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
kotlinx-coroutines-playServices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
insert-koin-koinCore = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
insert-koin-koinAndroid = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
insert-koin-koinCompose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
insert-koin-koinComposeViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
jakewharton-retrofit-retrofit2KotlinxSerializationConverter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }
squareup-okhttp3-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLoggingInterceptor" }

# Firebase
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-crashlyticsNdk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompose" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
compose = [
    "androidx-compose-material3",
    "androidx-compose-material-iconsExtended",
    "androidx-compose-runtime",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-animation",
    "androidx-compose-ui-toolingPreview",
    "androidx-compose-ui-tooling"
]
koin = [
    "insert-koin-koinCore",
    "insert-koin-koinAndroid",
    "insert-koin-koinCompose",
    "insert-koin-koinComposeViewmodel"
]
room = [
    "androidx-room-runtime",
    "androidx-room-ktx"
]